package acr.browser.lightning.compose

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

val primaryLight = Color(0xFF0059BB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0070EA)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF445E91)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA9C4FD)
val onSecondaryContainerLight = Color(0xFF355082)
val tertiaryLight = Color(0xFF954A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFF8200)
val onTertiaryContainerLight = Color(0xFF5F2C00)
val errorLight = Color(0xFFB81311)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDC3128)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFDF8F8)
val onBackgroundLight = Color(0xFF1C1B1B)
val surfaceLight = Color(0xFFFDF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFADC7FF)
val surfaceDimLight = Color(0xFFDDD9D8)
val surfaceBrightLight = Color(0xFFFDF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFFADC7FF)
val onPrimaryDark = Color(0xFF002E68)
val primaryContainerDark = Color(0xFF4A8EFF)
val onPrimaryContainerDark = Color(0xFF000516)
val secondaryDark = Color(0xFFADC7FF)
val onSecondaryDark = Color(0xFF102F5F)
val secondaryContainerDark = Color(0xFF2D487A)
val onSecondaryContainerDark = Color(0xFF9EB8F1)
val tertiaryDark = Color(0xFFFFB785)
val onTertiaryDark = Color(0xFF502400)
val tertiaryContainerDark = Color(0xFFFF8200)
val onTertiaryContainerDark = Color(0xFF5F2C00)
val errorDark = Color(0xFFFFB4A9)
val onErrorDark = Color(0xFF690002)
val errorContainerDark = Color(0xFFFF5545)
val onErrorContainerDark = Color(0xFF450001)
val backgroundDark = Color(0xFF141313)
val onBackgroundDark = Color(0xFFE5E2E1)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF005BC0)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)

val primaryDarkHighContrast = Color(0xFFF0F0F0)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onPrimaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val secondaryDarkHighContrast = Color(0xFFF0F0F0)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onSecondaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val tertiaryDarkHighContrast = Color(0xFFF0F0F0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onTertiaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF000000)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E2)
val surfaceDarkHighContrast = Color(0xFF000000)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF000000)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF9EDEF)
val outlineVariantDarkHighContrast = Color(0xFFCBC0C1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF484848)
val surfaceDimDarkHighContrast = Color(0xFF000000)
val surfaceBrightDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF000000)
val surfaceContainerDarkHighContrast = Color(0xFF000000)
val surfaceContainerHighDarkHighContrast = Color(0xFF000000)
val surfaceContainerHighestDarkHighContrast = Color(0xFF000000)

/**
 * Converts a [Color] to an RGB Hex String.
 */
fun Color.toRgbHexString(): String = toArgb().toHexString().substring(2)
